# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.15'

steps:
- task: UseDotNet@2
  displayName: 'Use dotnet 5'
  inputs:
    packageType: 'sdk'
    version: '5.x'

- task: CmdLine@2
  displayName: dotnet tool install PowerShell
  inputs:
    script: |
      dotnet --version
      dotnet new tool-manifest --force
      dotnet tool install PowerShell --version 6.2.4

